# version: '3'

# services:
#   backend:
#     build:
#       context: ./backend
#     container_name: backend
#     ports:
#       - "8080:8080"
#     restart: always
#     networks:
#       - spring_net
#       - frontend_net

#   frontend:
#     build: ./frontend
#     ports:
#       - 3000:3000
#     networks:
#       - frontend_net

# networks:
#   spring_net:
#   frontend_net:
version: "3"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adcalmesnil
      MONGO_INITDB_ROOT_PASSWORD: CW39GSOhLWu9m533

  movies-backend:
    container_name: movies-backend
    image: openjdk:17-jdk-alpine
    build: .
    volumes:
      - ./backend:/movies
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb+srv://adcalmesnil:CW39GSOhLWu9m533@cluster0.yavh18d.mongodb.net
      - DATABASE_USERNAME=adcalmesnil
      - DATABASE_PASSWORD=CW39GSOhLWu9m533
    depends_on:
      - mongo

  movie-client:
    image: node:latest
    container_name: movie-client
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    working_dir: /app
    depends_on:
      - movies-backend
